### ISSUE TITLE
Adding idle=poll to the kernel parameters

### ISSUE THREAD

**Issue by andresriancho** [seecurity/mona-timing-lib#3]
> On Ubuntu Linux machines, you can disable this feature by adding idle=poll to the kernel parameters.

Did you run tests with and without this parameter? Does it really impact the results? How much?

**Comment by seecurity** [comment]
I remember that I did measurements years ago and there were differences, but I didn't write it up. 

Please share if you get results!

**Comment by andresriancho** [comment]
Thanks for the quick response :+1: 

My code and experiments are at:
- https://github.com/andresriancho/pico
- https://github.com/andresriancho/pico/wiki
